<nav class="menu">
    <ul class="menu-items">
        <li class="menu-item">
            <a href="#" class="menu-link">Home</a>
        </li>
        <li class="menu-item">
            <a href="#" class="menu-link">About</a>
        </li>
        <li class="menu-item has-submenu">
            <a href="#" class="menu-link">Categories</a>
            <ul class="submenu lvl1">
                <li class="menu-item"><a href="#" class="menu-back">Back</a></li>
                <li class="menu-item has-submenu">
                    <a href="#" class="menu-link">Submenu Level 1</a>
                    <ul class="submenu lvl2">
                        <li class="menu-item"><a href="#" class="menu-back">Back</a></li>
                        <li class="menu-item"><a href="#" class="menu-link">Submenu Level 2</a></li>
                        <li class="menu-item"><a href="#" class="menu-link">Submenu Level 2</a></li>
                        <li class="menu-item"><a href="#" class="menu-link">Submenu Level 2</a></li>
                    </ul>
                </li>
                <li class="menu-item"><a href="#" class="menu-link">Submenu Level 1</a></li>
                <li class="menu-item"><a href="#" class="menu-link">Submenu Level 1</a></li>
            </ul>
        </li>
        <li class="menu-item">
            <a href="#" class="menu-link">Archives</a>
        </li>
        <li class="menu-item">
            <a href="#" class="menu-link">Contact</a>
        </li>
    </ul>
</nav>