<div class="posts">
    <div class="post bg-white">
        <header class="post-header">
            <h3>Power of Convenience - 3 Lessons You Can Learn from Retail Stores</h3>

            <div class="by">
                <i>by</i> <a href="#">Syed Balkhi</a> on August 6, 2013
            </div>
        </header>
        <section class="post-content">
            <img src="https://place-hold.it/800x300" alt="Image">
            <p>Convenience is a crucial element behind many decisions that we make in our daily life. You would be surprised by its true power if you closely monitor your purchases and the decisions made around you everyday. Today, I’ll share a story of an important lesson I learned about the power of convenience when I was…</p>
        </section>
        <footer class="post-footer">
            <div class="categories">
            Categories: <a href="#">Business</a>, <a href="#">Marketing</a>
            </div>
            <div class="continue-reading">
                <a href="#">Continue Reading »</a>
            </div>
        </footer>
    </div>
    <div class="post bg-white">
        <header class="post-header">
            <h3>Power of Convenience - 3 Lessons You Can Learn from Retail Stores</h3>

            <div class="by">
                <i>by</i> <a href="#">Syed Balkhi</a> on August 6, 2013
            </div>
        </header>
        <section class="post-content">
            <img src="https://place-hold.it/800x300" alt="Image">
            <p>Convenience is a crucial element behind many decisions that we make in our daily life. You would be surprised by its true power if you closely monitor your purchases and the decisions made around you everyday. Today, I’ll share a story of an important lesson I learned about the power of convenience when I was…</p>
        </section>
        <footer class="post-footer">
            <div class="categories">
            Categories: <a href="#">Business</a>, <a href="#">Marketing</a>
            </div>
            <div class="continue-reading">
                <a href="#">Continue Reading »</a>
            </div>
        </footer>
    </div>
    <div class="post bg-white">
        <header class="post-header">
            <h3>Power of Convenience - 3 Lessons You Can Learn from Retail Stores</h3>

            <div class="by">
                <i>by</i> <a href="#">Syed Balkhi</a> on August 6, 2013
            </div>
        </header>
        <section class="post-content">
            <img src="https://place-hold.it/800x300" alt="Image">
            <p>Convenience is a crucial element behind many decisions that we make in our daily life. You would be surprised by its true power if you closely monitor your purchases and the decisions made around you everyday. Today, I’ll share a story of an important lesson I learned about the power of convenience when I was…</p>
        </section>
        <footer class="post-footer">
            <div class="categories">
            Categories: <a href="#">Business</a>, <a href="#">Marketing</a>
            </div>
            <div class="continue-reading">
                <a href="#">Continue Reading »</a>
            </div>
        </footer>
    </div>
    <div class="post bg-white">
        <header class="post-header">
            <h3>Power of Convenience - 3 Lessons You Can Learn from Retail Stores</h3>

            <div class="by">
                <i>by</i> <a href="#">Syed Balkhi</a> on August 6, 2013
            </div>
        </header>
        <section class="post-content">
            <img src="https://place-hold.it/800x300" alt="Image">
            <p>Convenience is a crucial element behind many decisions that we make in our daily life. You would be surprised by its true power if you closely monitor your purchases and the decisions made around you everyday. Today, I’ll share a story of an important lesson I learned about the power of convenience when I was…</p>
        </section>
        <footer class="post-footer">
            <div class="categories">
            Categories: <a href="#">Business</a>, <a href="#">Marketing</a>
            </div>
            <div class="continue-reading">
                <a href="#">Continue Reading »</a>
            </div>
        </footer>
    </div>
</div>